### ISSUE TITLE
Successfully ran pyimagesearch code on at least 1 GSV image

### ISSUE THREAD

**Issue by ishacusp** [ishacusp/ARGO_Labs#1]
Location: (location: 1 2nd avenue).

Results: Since the image is blurred, the segmentation seems weak.

**Comment by vr00n** [comment]
1. I cant seem to find the results of the segmentation.
2. Maybe you can crop or adjust the imagery to reduce blurring.

**Comment by ishacusp** [comment]
https://github.com/ishacusp/ARGO_Labs/blob/master/opencv-semantic-segmentation/Results/Screen%20Shot%202018-10-07%20at%207.45.10%20AM.png
